<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>ec72636d-1315-45f6-a78e-5ad1147debd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nextenterproductdata</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='nextenterproductdata']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f1e226ac-0f2b-47c5-baf7-af510235b6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nextenterproductdata</value>
      <webElementGuid>62fb3a03-593b-453b-9ca4-3c781022a7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Next (Enter Product Data)</value>
      <webElementGuid>548eb78d-d1ff-4cb7-ba00-238e50ae03c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a261f685-6cb4-4f1f-83d7-a00efa34f8d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>next</value>
      <webElementGuid>429aaca0-d0bc-435b-81f3-1d76b2b43e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next »</value>
      <webElementGuid>f8f90b0a-7bb1-4f1f-8c1d-9b14f267510f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nextenterproductdata&quot;)</value>
      <webElementGuid>7d779ff8-401f-4a55-9aed-9b5922d1c409</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='nextenterproductdata']</value>
      <webElementGuid>948fb497-6fa8-4eec-89d1-38e3a3cfd8dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insurance-form']/div/section[2]/div[13]/button[2]</value>
      <webElementGuid>518cbac2-8126-45d9-90de-9939693ee52a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='« Prev'])[1]/following::button[1]</value>
      <webElementGuid>3475405f-4e73-4aac-aa1b-6ad9be0f75be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[1]/following::button[2]</value>
      <webElementGuid>34b84aeb-3a83-4af7-865f-0c757b932952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Date'])[1]/preceding::button[1]</value>
      <webElementGuid>bb40a133-d406-4613-8547-3ed18b95fa68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is mandatory'])[1]/preceding::button[2]</value>
      <webElementGuid>4f998658-9606-4efe-a47f-ed3561890976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>4196789b-98cc-4c95-becb-7ee43a97f9c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'nextenterproductdata' and @name = 'Next (Enter Product Data)' and @type = 'button' and (text() = 'Next »' or . = 'Next »')]</value>
      <webElementGuid>99a925a1-5b27-49c6-8ec9-28d0a03707e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
