<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Date of Birth_Open Date of Birth Calender</name>
   <tag></tag>
   <elementGuidId>b152d902-3434-44ac-8944-b1eac7f4132e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#opendateofbirthcalender</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='opendateofbirthcalender']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>edeadc8d-c3c5-468a-b211-9ffdb12f3b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d380a4f9-ad92-416e-baa0-4be84234dc6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-datepicker-trigger</value>
      <webElementGuid>275685e2-ca41-4aea-b601-8db0809d51bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Open Date of Birth Calender</value>
      <webElementGuid>f94ed3fc-458d-40d9-91a6-862ed41283d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Open Date of Birth Calender</value>
      <webElementGuid>c5d3e375-f5fb-4f2f-b3d3-4821e72ba405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>opendateofbirthcalender</value>
      <webElementGuid>7e19e85a-34f3-4d81-accd-df88d03b9676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opendateofbirthcalender&quot;)</value>
      <webElementGuid>c54abeca-cb95-4c13-8165-722eea99018f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='opendateofbirthcalender']</value>
      <webElementGuid>d7472aad-5adf-47ae-b996-6b5ca58a87ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insurance-form']/div/section[2]/div[3]/button</value>
      <webElementGuid>62787247-4d15-4721-91a2-4bd564c412a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Birth'])[1]/following::button[1]</value>
      <webElementGuid>cfb5027d-7d80-41b0-8101-9dd989303bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be at least 2 characters long and must only contain letters'])[2]/following::button[1]</value>
      <webElementGuid>614fe5f1-4f73-4e62-b2db-b395dfc567d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is mandatory'])[1]/preceding::button[1]</value>
      <webElementGuid>cc88c454-45c3-49a4-8f61-32c5d0332739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/preceding::button[1]</value>
      <webElementGuid>3b229acd-480c-448d-bbab-7d24f6a39f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div[3]/button</value>
      <webElementGuid>52263f09-cbee-43da-a8c9-51e5b2cd7ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'Open Date of Birth Calender' and @title = 'Open Date of Birth Calender' and @id = 'opendateofbirthcalender']</value>
      <webElementGuid>19380c1a-d2f6-4b42-85c7-5532a84b5408</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
