<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Website_Website</name>
   <tag></tag>
   <elementGuidId>032b9b1a-f53f-4f2d-bc6d-5ea74ffa2526</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#website</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='website']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e05029e4-cd1c-495e-a0fc-d9a3045467f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>website</value>
      <webElementGuid>172fb69b-9398-45f8-8be5-06587dbe4b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Website</value>
      <webElementGuid>8a73b853-a5ee-407a-a597-7a912ff76683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>df5ef683-2451-4250-997c-b9a2d071048f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;website&quot;)</value>
      <webElementGuid>9bc9b1d9-ebbf-402e-b706-902555982952</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='website']</value>
      <webElementGuid>16b6e369-9581-476c-a740-38d0fbf4e3a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insurance-form']/div/section[2]/div[11]/input</value>
      <webElementGuid>78ea833c-396a-4a00-a1f9-2e82f92205ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/input</value>
      <webElementGuid>716d1b11-eca2-4e74-8736-4107538d4310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'website' and @name = 'Website' and @type = 'text']</value>
      <webElementGuid>994a411c-bbc5-4ee6-ac2a-c563167a75c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
