<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Street Address_Street Address</name>
   <tag></tag>
   <elementGuidId>de468682-d5f2-41c9-adb1-c636f9b1af26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#streetaddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='streetaddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f32b0a45-2d30-4127-8600-166c9f628bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>streetaddress</value>
      <webElementGuid>ed8ccd3a-a331-4813-8356-f98fb3f7d406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Street Address</value>
      <webElementGuid>17345f22-6d5d-4525-8268-db2590876d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>446eaebc-7b4a-499b-9f27-8fe98b1f6832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;streetaddress&quot;)</value>
      <webElementGuid>b7adcc14-ad88-4424-a989-5b79c7f17ad6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='streetaddress']</value>
      <webElementGuid>b60a6380-48a0-4d17-8cf5-90f7119776e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insurance-form']/div/section[2]/div[5]/input</value>
      <webElementGuid>9a08d568-da5f-4121-89ed-b710270680b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>3ded7a41-352d-4248-9db5-25b3bc7da2ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'streetaddress' and @name = 'Street Address' and @type = 'text']</value>
      <webElementGuid>85d52543-255c-4bff-b94e-ffc0f6d538f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
