<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Male_ideal-radio</name>
   <tag></tag>
   <elementGuidId>e0fefd28-c981-4201-b879-0b86b013a5db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ideal-radio</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='insurance-form']/div/section[2]/div[4]/p/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f0d5377b-7d26-4d43-a404-9cb7133d7fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ideal-radio</value>
      <webElementGuid>d6186df2-ee58-429a-8163-a9380dee9c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;insurance-form&quot;)/div[@class=&quot;idealsteps-wrap&quot;]/section[@class=&quot;idealsteps-step&quot;]/div[@class=&quot;field&quot;]/p[@class=&quot;group&quot;]/label[@class=&quot;ideal-radiocheck-label&quot;]/span[@class=&quot;ideal-radio&quot;]</value>
      <webElementGuid>c02a171b-f374-45e8-a8ac-806126239c7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insurance-form']/div/section[2]/div[4]/p/label/span</value>
      <webElementGuid>db5257b3-00d9-46e9-b96b-878ab553864c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>82845774-e46a-4ff1-a1c0-c3bbea617047</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
