<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Speeding_ideal-check</name>
   <tag></tag>
   <elementGuidId>496285e8-f551-4296-966b-9435d64297a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ideal-check</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='insurance-form']/div/section[2]/div[10]/p/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7e774b6f-0387-4d80-ba07-62035291f63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ideal-check</value>
      <webElementGuid>7310e64b-c967-4d52-bfc5-dcbd3cce8d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;insurance-form&quot;)/div[@class=&quot;idealsteps-wrap&quot;]/section[@class=&quot;idealsteps-step&quot;]/div[@class=&quot;field idealforms-field idealforms-field-checkbox&quot;]/p[@class=&quot;group&quot;]/label[@class=&quot;ideal-radiocheck-label&quot;]/span[@class=&quot;ideal-check&quot;]</value>
      <webElementGuid>e6a85b5e-6f17-49b8-ad6f-cf2bc6fb834f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insurance-form']/div/section[2]/div[10]/p/label/span</value>
      <webElementGuid>d4010b1f-aea3-483b-8743-1634b8507c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/p/label/span</value>
      <webElementGuid>8d90c575-530b-4097-bf0a-c0f1ab2a3d09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
