<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Payment Confirmation_os-icon os-icon-ui-46</name>
   <tag></tag>
   <elementGuidId>7144b2cf-87d5-4af1-bdca-2d48960be4c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.os-icon.os-icon-ui-46</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>0141e7e2-96c2-44c4-bef0-a18ad5038723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>os-icon os-icon-ui-46</value>
      <webElementGuid>4bb8092e-9812-4ece-80c7-286d121648f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;menu-position-side menu-side-left full-screen&quot;]/div[@class=&quot;all-wrapper solid-bg-all&quot;]/div[@class=&quot;top-bar color-scheme-bright&quot;]/div[@class=&quot;top-menu-controls&quot;]/div[@class=&quot;top-icon top-settings os-dropdown-trigger os-dropdown-position-left&quot;]/i[@class=&quot;os-icon os-icon-ui-46&quot;]</value>
      <webElementGuid>f201eb53-6a0e-4ab3-8662-f3c2f0aaacf7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/i</value>
      <webElementGuid>d1b3bdfe-f27f-406c-9293-7ab49e37d139</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
