<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>7b559a1b-f614-4061-aac8-d90cee333ccb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nextenterinsurantdata</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='nextenterinsurantdata']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>98416d76-facd-47e8-bee1-faea217c09f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nextenterinsurantdata</value>
      <webElementGuid>1a708ea7-2aac-497e-b06f-8c35b269c551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Next (Enter Insurant Data)</value>
      <webElementGuid>d37d7f02-9296-4568-bb79-5178afd5f0d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8b141745-3926-4616-88ef-3d867786384a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>next button</value>
      <webElementGuid>2ae62acc-5ff4-46b7-980e-0aaa0f5b0aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next »</value>
      <webElementGuid>978b6e1c-dc00-4760-82b4-7c637e86a6bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nextenterinsurantdata&quot;)</value>
      <webElementGuid>04d4a835-e5a9-4a5f-87e9-5e1ff0258b5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='nextenterinsurantdata']</value>
      <webElementGuid>5c10e98c-76cb-4b2d-a014-9b1a84a318a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insurance-form']/div/section/div[9]/button</value>
      <webElementGuid>d526d39c-5dd9-47c0-966e-607be5cc7034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be a number between 100 and 100000'])[1]/following::button[1]</value>
      <webElementGuid>9235618e-a321-4f65-8834-34a2482681e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Annual Mileage [mi]'])[1]/following::button[1]</value>
      <webElementGuid>4f7d6d6c-f6b0-4ba2-a1c0-0bfcec959d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/preceding::button[1]</value>
      <webElementGuid>bcd04d88-ad2d-4b1d-a4c6-4172398f1bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is mandatory'])[1]/preceding::button[1]</value>
      <webElementGuid>0af6081b-093d-4f13-9311-085bbdab3b6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next »']/parent::*</value>
      <webElementGuid>78f465b3-e2e3-4786-9865-0892df32df69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/button</value>
      <webElementGuid>1ea519c5-412a-437d-a4bf-63b42c078b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'nextenterinsurantdata' and @name = 'Next (Enter Insurant Data)' and @type = 'button' and (text() = 'Next »' or . = 'Next »')]</value>
      <webElementGuid>bbb07909-a337-442f-93c0-99d12c56adea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
