<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_License Plate Number_License Plate Number</name>
   <tag></tag>
   <elementGuidId>f985749d-29d1-423d-bcca-e6ebb888ad61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#licenseplatenumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='licenseplatenumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be1b97c7-6e51-47b1-8c43-e5a08ca6de8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>licenseplatenumber</value>
      <webElementGuid>c76097ad-fa89-4235-8bdc-8d57bc373ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>License Plate Number</value>
      <webElementGuid>ae73f4ca-238e-4c18-b106-16330b0eb7b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4ca66289-8715-4423-ac3b-0d0d5ddac1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;licenseplatenumber&quot;)</value>
      <webElementGuid>34e0fb8b-13be-49b9-83a5-d8b657295b1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='licenseplatenumber']</value>
      <webElementGuid>09ff4004-5dcf-42e9-babf-73281d42c227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insurance-form']/div/section/div[7]/input</value>
      <webElementGuid>06c21c7d-b818-4ce3-b57f-7ded95df1039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>ec0efd98-2981-4b4b-8b3f-259229a3addd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'licenseplatenumber' and @name = 'License Plate Number' and @type = 'text']</value>
      <webElementGuid>c1c2a4fb-4c61-48d6-891f-72c0bbc9a881</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
