<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of Manufacture_Date of Manufacture</name>
   <tag></tag>
   <elementGuidId>3a81e5c2-a299-4249-a974-04c1a48018a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dateofmanufacture</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dateofmanufacture']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90d53333-41a8-46e6-b054-a9d38330d928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dateofmanufacture</value>
      <webElementGuid>2118bdaa-ec5b-485d-b554-04ff42647548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Date of Manufacture</value>
      <webElementGuid>e5d82185-0e0f-40ed-8291-f3310ed2f87f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>78edf5b2-2286-41e7-a6f5-c97254c033ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM/DD/YYYY</value>
      <webElementGuid>90862e80-71ba-4120-b1ab-2e34f5035e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepicker hasDatepicker</value>
      <webElementGuid>77cd0ce4-1c55-4ac9-956a-8cbf14607d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dateofmanufacture&quot;)</value>
      <webElementGuid>30543242-265e-411c-819a-237792158654</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dateofmanufacture']</value>
      <webElementGuid>3d8ff94d-c328-4992-b52e-dcad51b8c4bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insurance-form']/div/section/div[3]/input</value>
      <webElementGuid>98b83cf7-9848-486f-a752-e15be6a79082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>d150f5ff-7490-41d3-8a5d-0a8a37171713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dateofmanufacture' and @name = 'Date of Manufacture' and @type = 'text' and @placeholder = 'MM/DD/YYYY']</value>
      <webElementGuid>0eeef2b8-16a6-4c37-ae50-4ec26d153ce6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
