<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Engine Performance kW_kW</name>
   <tag></tag>
   <elementGuidId>c2d7be1a-324d-46f3-a52d-26ada586b3e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#engineperformance</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='engineperformance']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6157b541-4029-439f-acee-9b1575c21ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>engineperformance</value>
      <webElementGuid>312a366b-cd12-4b8a-9c44-a057472ee36a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>[kW]</value>
      <webElementGuid>4010e98f-16f3-4db0-937b-16ddd40a29fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fd9183ce-2831-4561-9a04-983156007eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;engineperformance&quot;)</value>
      <webElementGuid>2a970fd0-de05-4ef3-aa1f-3b54d5c2503c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='engineperformance']</value>
      <webElementGuid>e695fded-f671-4501-92d9-725cd9ae083a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insurance-form']/div/section/div[2]/input</value>
      <webElementGuid>3e1e84a0-953b-4daf-9210-df1f6232617b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>2f48c78a-79f2-43e8-9075-1d97c1188e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'engineperformance' and @name = '[kW]' and @type = 'text']</value>
      <webElementGuid>3169b947-5e72-4b38-9ca0-05bc364f2346</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
