<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_List Price_List Price</name>
   <tag></tag>
   <elementGuidId>7704f56a-e206-4625-800a-00e0f45e7240</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#listprice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='listprice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c81baadd-63a8-4ab5-b422-21c334973dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>listprice</value>
      <webElementGuid>f078bfe0-9db2-43e4-9a6f-07b4c5e6fc3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>List Price</value>
      <webElementGuid>f58734aa-0f3e-45cc-8267-bb1244cf25b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>06c0d46e-ca82-4f82-b923-995f2baa007c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;listprice&quot;)</value>
      <webElementGuid>7ce4cacf-2d4d-492e-b18f-73864eee90b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='listprice']</value>
      <webElementGuid>40e1dbd7-0d29-4421-b33c-29030cc7ae6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insurance-form']/div/section/div[6]/input</value>
      <webElementGuid>863570c9-5737-4fac-bd1e-4b818f0966a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>518897a5-467d-4e1c-a648-69270ab34d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'listprice' and @name = 'List Price' and @type = 'text']</value>
      <webElementGuid>c2b05d98-124e-422d-81a1-272547197885</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
