<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Annual Mileage mi_Annual Mileage</name>
   <tag></tag>
   <elementGuidId>5c791436-2360-40fe-89aa-a8c08c0cb610</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#annualmileage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='annualmileage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b823a6f-5029-455c-9bea-1454829049c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>annualmileage</value>
      <webElementGuid>0ca2684c-e5b7-49d5-ae24-51412931275a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Annual Mileage</value>
      <webElementGuid>75b38bdc-d4b5-486f-9aaa-b0a199040577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c04b1fbb-0462-4eee-95f6-57e257bb1d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;annualmileage&quot;)</value>
      <webElementGuid>886b1345-534f-4383-bd83-d8ff72c83f14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='annualmileage']</value>
      <webElementGuid>3c38ce60-85c1-4967-86ac-969b5f949730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insurance-form']/div/section/div[8]/input</value>
      <webElementGuid>a07caef2-2ea6-41bb-a543-366131e09b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>8f4ca780-d826-40ca-a539-c14f5c786cf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'annualmileage' and @name = 'Annual Mileage' and @type = 'text']</value>
      <webElementGuid>76245030-b574-4539-8b54-a3f95868c01e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
