<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_please select                       _9e925e</name>
   <tag></tag>
   <elementGuidId>9b180e23-46c3-4fa4-b764-164a263b6cd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#numberofseats</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='numberofseats']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0cca5617-546d-419e-9ced-3e411a8aa642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>numberofseats</value>
      <webElementGuid>da9ee2cf-974c-45ab-9fd2-462844adba46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Number of Seats</value>
      <webElementGuid>3b8f181b-b23f-4b88-9ed3-b46ca81842f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            – please select –
                                            1
                                            2
                                            3
                                            4
                                            5
                                            6
                                            7
                                            8
                                            9
                                        </value>
      <webElementGuid>0249aba9-b194-4764-8e0c-026b2b467141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;numberofseats&quot;)</value>
      <webElementGuid>bb2e68fc-ad4d-46f4-88c1-a38ff97c2913</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='numberofseats']</value>
      <webElementGuid>91a9579f-d673-4b87-b60e-b860c082a360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='insurance-form']/div/section/div[4]/select</value>
      <webElementGuid>79ff8e57-4a58-4ad3-add0-8cf50ec15fd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of Seats'])[1]/following::select[1]</value>
      <webElementGuid>e09f8461-6f43-4b94-80d6-8f7500f6c93d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Must be today or somewhere in the past'])[1]/following::select[1]</value>
      <webElementGuid>7deb79fb-3ca0-45fb-9625-3ff099b4913a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select an option'])[2]/preceding::select[1]</value>
      <webElementGuid>3040b8b8-9ef2-4950-9426-394feee8a293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fuel Type'])[1]/preceding::select[1]</value>
      <webElementGuid>dc9668ff-beb9-4889-bf85-52b242421862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
      <webElementGuid>10a76075-619b-470d-8cc5-fd95b04a50d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'numberofseats' and @name = 'Number of Seats' and (text() = '
                                            – please select –
                                            1
                                            2
                                            3
                                            4
                                            5
                                            6
                                            7
                                            8
                                            9
                                        ' or . = '
                                            – please select –
                                            1
                                            2
                                            3
                                            4
                                            5
                                            6
                                            7
                                            8
                                            9
                                        ')]</value>
      <webElementGuid>6affcbe2-705c-46c3-945c-81afeaa89c88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
