<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Microsoft Office  50.00_product_attri_560d4c</name>
   <tag></tag>
   <elementGuidId>014abcb5-e6f3-4fe1-bcc9-79e4846a2273</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product_attribute_16_8_8_23</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product_attribute_16_8_8_23']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ccc40ea-b695-424a-8a3b-e2568d644591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_attribute_16_8_8_23</value>
      <webElementGuid>2efb7110-cc46-409a-8b3f-0850eaafe3ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>df7ff9c2-2b0e-42c6-a953-21ba62d4ffa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product_attribute_16_8_8</value>
      <webElementGuid>dd329bbd-148a-41fe-a1af-c3fc46054623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>23</value>
      <webElementGuid>89c3db40-84e2-44fe-8347-b7d2911b3c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_attribute_16_8_8_23&quot;)</value>
      <webElementGuid>586f8e91-8fee-47ac-96d7-c46c494fedcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_attribute_16_8_8_23']</value>
      <webElementGuid>5a88f3b9-8075-4a15-b91a-aebf85238645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div/div/div[2]/div[6]/dl/dd[5]/ul/li[2]/input</value>
      <webElementGuid>c91b7127-8f1d-4cdd-ab46-9ce7f4f0a59d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dd[5]/ul/li[2]/input</value>
      <webElementGuid>5df0b9cf-014a-4f7d-ab0b-87f604020e7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'product_attribute_16_8_8_23' and @type = 'checkbox' and @name = 'product_attribute_16_8_8']</value>
      <webElementGuid>7ff55b5c-2a4f-47d6-a403-d7389b99bca4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
