<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__product_attribute_16_3_6</name>
   <tag></tag>
   <elementGuidId>c974155d-ad22-4724-8ea6-666ea73f70d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product_attribute_16_3_6_19</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product_attribute_16_3_6_19']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9eba775b-bb33-4071-8981-df015ee7cba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_attribute_16_3_6_19</value>
      <webElementGuid>17538e8f-fb56-4d82-940d-973a176bbd0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>296cca4f-dda9-41ee-bd24-7ccbe037e980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product_attribute_16_3_6</value>
      <webElementGuid>edbee5c6-160d-45f7-97b5-3cf8ab494821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>86a804ee-b67c-4b40-953d-0b8a873c86c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_attribute_16_3_6_19&quot;)</value>
      <webElementGuid>05042d7c-2dec-41a3-a723-1cdf3dc31495</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product_attribute_16_3_6_19']</value>
      <webElementGuid>0a1c9538-e39e-4ac2-9888-4e14be6255e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div/div/div[2]/div[6]/dl/dd[3]/ul/li[2]/input</value>
      <webElementGuid>6915a6de-a1ae-4c5a-983b-7f66043f1e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/input</value>
      <webElementGuid>7f17e664-3037-4575-9a67-ea3aa8eb0b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'product_attribute_16_3_6_19' and @type = 'radio' and @name = 'product_attribute_16_3_6']</value>
      <webElementGuid>b8bb304e-1d85-49c5-984c-b28ad0c44552</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
