<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Automobile</name>
   <tag></tag>
   <elementGuidId>e6243d9e-2cd9-4d0f-86a4-494feecd1fc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav_automobile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav_automobile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>98171dcc-b7df-441a-8f9c-d74f55884126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav_automobile</value>
      <webElementGuid>33bbaf11-f31a-4abe-bc6e-aa64687d8c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Navigation Automobile</value>
      <webElementGuid>55ef80bf-7378-44c6-8db9-8c43f4b8545c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>b46f5090-d95b-462c-ba10-ef264e0ba3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>gotoapp('Automobile');</value>
      <webElementGuid>7dd211e0-c884-4d1b-97e4-9efed65c73a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automobile</value>
      <webElementGuid>d82e5568-dad3-4af5-aead-db00eb328362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-content&quot;)/header[@class=&quot;site-header&quot;]/div[@class=&quot;bottom-header&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;main-navigation&quot;]/ul[@class=&quot;menu&quot;]/li[@class=&quot;menu-item&quot;]/a[@id=&quot;nav_automobile&quot;]</value>
      <webElementGuid>3e711ce6-dbb1-4495-92a7-79910f78bddb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav_automobile']</value>
      <webElementGuid>70740063-a24b-482c-b02a-2e4731571e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/header/div[2]/div/div/ul/li/a</value>
      <webElementGuid>ac4df128-5182-497f-9c44-5d02add81d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Automobile')]</value>
      <webElementGuid>70d841c8-3aa6-4681-aa1d-f0bc7d79e371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit Support!'])[1]/following::a[1]</value>
      <webElementGuid>7350dd89-9ce4-464d-b326-fc926bc3c261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This is a sample application, Version 1.0.1'])[1]/following::a[2]</value>
      <webElementGuid>db10ba48-5ea3-48f5-abe7-50d2d2ffc504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request Demo'])[1]/preceding::a[4]</value>
      <webElementGuid>bfa290ef-4aec-4d5a-9899-64a604dcb94c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Automobile']/parent::*</value>
      <webElementGuid>3b3e07ce-45c6-4fd1-b466-632c9fa949b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>b2851703-2b86-4ce2-bf4a-f9c206412752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>b8d390e4-b8df-4846-8dd6-65dfba98b3d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'nav_automobile' and @name = 'Navigation Automobile' and @href = '#' and (text() = 'Automobile' or . = 'Automobile')]</value>
      <webElementGuid>2bba5a97-00a1-4ee1-9e07-c133193f1c20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
