<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign up below to find out more_email_address</name>
   <tag></tag>
   <elementGuidId>50aa55a8-792a-4235-b215-a4418d9975ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email_address&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email_address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b32563d6-cbfe-41d7-ae2e-d3e049bbc43e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bb110ade-da8a-49bb-8ac1-dcab94728f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formkit-input</value>
      <webElementGuid>b46d70c6-413c-4ae3-aac4-653a0e8030f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email_address</value>
      <webElementGuid>22af4752-fbe3-4802-b874-8138e4b6813b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Email Address</value>
      <webElementGuid>938f2e74-039e-4cb9-8a55-312077179b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email Address</value>
      <webElementGuid>4ac873be-3255-424e-8448-34b62f20bdd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js&quot;]/body[@class=&quot;page-template-default page page-id-579 et-tb-has-template et-tb-has-header et_button_custom_icon et_pb_button_helper_class et_pb_footer_columns1 et_cover_background et_pb_gutter windows et_pb_gutters2 et_pb_pagebuilder_layout et_no_sidebar et_divi_theme et-db chrome&quot;]/div[@class=&quot;formkit-slide-in&quot;]/form[@class=&quot;seva-form formkit-form&quot;]/div[2]/div[@class=&quot;seva-fields formkit-fields&quot;]/div[@class=&quot;formkit-field&quot;]/input[@class=&quot;formkit-input&quot;]</value>
      <webElementGuid>f542f8d9-c6e0-497a-92e0-91c20d4e168b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email_address']</value>
      <webElementGuid>4799fd8f-9e7d-4acc-ab04-fd78e5e76b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>c78adca5-b86f-4a8d-9cb4-525e5a24d88c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'email_address' and @placeholder = 'Email Address']</value>
      <webElementGuid>386bb541-1194-4fa4-b253-1ddaf8ac03a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
