<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address_et_pb_contact_email_0</name>
   <tag></tag>
   <elementGuidId>092bd3b6-fc3a-42c4-a1a0-5ba45a1e2e6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#et_pb_contact_email_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='et_pb_contact_email_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c05fbca4-6b32-4900-85e7-8878cc188166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6551705c-a230-414c-9287-7f97147a5baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>et_pb_contact_email_0</value>
      <webElementGuid>809391a3-7e37-438c-b867-40242a6ef60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f294b8e-5726-4785-8e0a-8b1c9c12f3c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>et_pb_contact_email_0</value>
      <webElementGuid>f38483df-0e92-4657-b70d-2811af32103d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-required_mark</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>be6f6578-2631-4794-9c99-587cfdc4f743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field_type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>3b5e6083-366c-4463-b633-f5dc6e7d0e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original_id</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>3fd45985-a011-4cc4-a31f-9be4c7351dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email Address</value>
      <webElementGuid>59a93fbd-aba3-4fb1-86c4-52c0cdee0fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;et_pb_contact_email_0&quot;)</value>
      <webElementGuid>70c07e8e-c215-4800-a453-ddd6aec2e8b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='et_pb_contact_email_0']</value>
      <webElementGuid>0a7e18c5-b2c1-4d74-a443-af27b7967730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='et_pb_contact_form_0']/div[2]/form/p[2]/input</value>
      <webElementGuid>99cf4186-7921-4c37-8576-d5517131504d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/p[2]/input</value>
      <webElementGuid>d5fd5485-08b4-4ba3-ab1f-a57f8b4bcc6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'et_pb_contact_email_0' and @name = 'et_pb_contact_email_0' and @placeholder = 'Email Address']</value>
      <webElementGuid>6030b109-86e4-4ff0-8574-df23e7857deb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
